// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_history.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUserHistory = `-- name: CountUserHistory :one
SELECT COUNT(*) 
FROM game_history 
WHERE user_id = $1
`

func (q *Queries) CountUserHistory(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserHistory, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameHistory = `-- name: CreateGameHistory :one
INSERT INTO game_history (
    user_id,
    puzzle_digits,
    solution_expression,
    is_solved,
    time_taken_ms,
    is_daily_challenge
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, created_at, puzzle_digits, solution_expression, is_solved, time_taken_ms, is_daily_challenge
`

type CreateGameHistoryParams struct {
	UserID             uuid.NullUUID
	PuzzleDigits       string
	SolutionExpression string
	IsSolved           sql.NullBool
	TimeTakenMs        int32
	IsDailyChallenge   sql.NullBool
}

func (q *Queries) CreateGameHistory(ctx context.Context, arg CreateGameHistoryParams) (GameHistory, error) {
	row := q.db.QueryRowContext(ctx, createGameHistory,
		arg.UserID,
		arg.PuzzleDigits,
		arg.SolutionExpression,
		arg.IsSolved,
		arg.TimeTakenMs,
		arg.IsDailyChallenge,
	)
	var i GameHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.PuzzleDigits,
		&i.SolutionExpression,
		&i.IsSolved,
		&i.TimeTakenMs,
		&i.IsDailyChallenge,
	)
	return i, err
}

const getGlobalRecentGames = `-- name: GetGlobalRecentGames :many
SELECT gh.id, u.username, gh.time_taken_ms, gh.created_at
FROM game_history gh
JOIN users u ON gh.user_id = u.id
WHERE gh.is_solved = true
ORDER BY gh.created_at DESC
LIMIT 10
`

type GetGlobalRecentGamesRow struct {
	ID          uuid.UUID
	Username    string
	TimeTakenMs int32
	CreatedAt   time.Time
}

func (q *Queries) GetGlobalRecentGames(ctx context.Context) ([]GetGlobalRecentGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGlobalRecentGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalRecentGamesRow
	for rows.Next() {
		var i GetGlobalRecentGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TimeTakenMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserHistory = `-- name: GetUserHistory :many
SELECT 
    id, 
    puzzle_digits, 
    solution_expression, 
    is_solved, 
    time_taken_ms, 
    created_at
FROM game_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserHistoryParams struct {
	UserID uuid.NullUUID
	Limit  int32
	Offset int32
}

type GetUserHistoryRow struct {
	ID                 uuid.UUID
	PuzzleDigits       string
	SolutionExpression string
	IsSolved           sql.NullBool
	TimeTakenMs        int32
	CreatedAt          time.Time
}

func (q *Queries) GetUserHistory(ctx context.Context, arg GetUserHistoryParams) ([]GetUserHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserHistoryRow
	for rows.Next() {
		var i GetUserHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PuzzleDigits,
			&i.SolutionExpression,
			&i.IsSolved,
			&i.TimeTakenMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
