// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_stats.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getLeaderboardByStreak = `-- name: GetLeaderboardByStreak :many
SELECT u.username, s.current_streak
FROM user_stats s
JOIN users u ON s.user_id = u.id
ORDER BY s.current_streak DESC
LIMIT 10
`

type GetLeaderboardByStreakRow struct {
	Username      string
	CurrentStreak sql.NullInt32
}

func (q *Queries) GetLeaderboardByStreak(ctx context.Context) ([]GetLeaderboardByStreakRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboardByStreak)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardByStreakRow
	for rows.Next() {
		var i GetLeaderboardByStreakRow
		if err := rows.Scan(&i.Username, &i.CurrentStreak); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardByWins = `-- name: GetLeaderboardByWins :many
SELECT u.username, s.total_wins, s.total_games_played
FROM user_stats s
JOIN users u ON s.user_id = u.id
ORDER BY s.total_wins DESC
LIMIT 10
`

type GetLeaderboardByWinsRow struct {
	Username         string
	TotalWins        sql.NullInt32
	TotalGamesPlayed sql.NullInt32
}

func (q *Queries) GetLeaderboardByWins(ctx context.Context) ([]GetLeaderboardByWinsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboardByWins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardByWinsRow
	for rows.Next() {
		var i GetLeaderboardByWinsRow
		if err := rows.Scan(&i.Username, &i.TotalWins, &i.TotalGamesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, total_games_played, total_wins, current_streak, max_streak, fastest_solve_time_ms, updated_at FROM user_stats WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalGamesPlayed,
		&i.TotalWins,
		&i.CurrentStreak,
		&i.MaxStreak,
		&i.FastestSolveTimeMs,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatsLoss = `-- name: UpdateUserStatsLoss :exec
UPDATE user_stats
SET 
    total_games_played = total_games_played + 1,
    current_streak = 0,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) UpdateUserStatsLoss(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserStatsLoss, userID)
	return err
}

const updateUserStatsWin = `-- name: UpdateUserStatsWin :exec
UPDATE user_stats
SET 
    total_games_played = total_games_played + 1,
    total_wins = total_wins + 1,
    current_streak = current_streak + 1,
    max_streak = GREATEST(max_streak, current_streak + 1),
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) UpdateUserStatsWin(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserStatsWin, userID)
	return err
}
